# Server configuration
server.port=8082
server.servlet.context-path=/api

# Spring Boot configuration
spring.application.name=cuenta-movimiento-ms

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_db
spring.datasource.username=postgres
spring.datasource.password=Wilson_1988
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.banco.cuentamovimiento=DEBUG

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.connection-timeout=5000